name: to_do_list
description: To do list
version: 0.1.0

publish_to: none
environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  carousel:
    git:
      url: https://github.com/Iconica-Development/carousel
      ref: 0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
